[package]
name = "dapplication"
version = "0.1.0"
edition = "2021"

[dependencies]
ddomain = { path = "../ddomain" }
serde = { workspace = true }
ratatui = { workspace = true }
color-eyre = { workspace = true }
chrono = { workspace = true }