[package]
name = "ddomain"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
serde = { workspace = true }
ratatui = { workspace = true }
color-eyre = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }